### ISSUE TITLE
Subir los archivos de datos generados para el TP

### ISSUE THREAD

**Issue by ColtMoons** [ColtMoons/TF-20181B702-201923809#4]
Subir todos los archivos de datos (.csv) obtenidos para el Trabajo Parcial.

**Comment by Apolosmllb** [comment]
subir implementación de grafos close #3
[CódigoGrafoCiudad.txt](https://github.com/ColtMoons/TF-20181B702-201923809/files/8823977/CodigoGrafoCiudad.txt)
